name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "LICENSE"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE.md"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for correct Git history

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
          cache-version: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Cache Jekyll builds
        uses: actions/cache@v4
        with:
          path: _site
          key: jekyll-site-${{ github.sha }}
          restore-keys: |
            jekyll-site-

      - name: Build with Jekyll
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Test site
        run: |
          bundle exec htmlproofer _site \
            --disable-external \
            --check-html \
            --allow_hash_href \
            --check-img-http

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
